# Generated by Django 4.1.1 on 2022-09-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='auth', max_length=128),
            preserve_default=False,
        ),
    ]
