# Generated by Django 4.1.1 on 2022-09-13 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 20, 55, 20, 927287)),
        ),
    ]
